const LOGIN = {
  LOAD: "LOGIN_LOAD",
  LOAD_SUCCESS: "LOGIN_LOAD_SUCCESS",
  LOAD_FAIL: "LOGIN_LOAD_FAIL",
};
const COURSE = {
  LOAD: "COURSE_LOAD",
  LOAD_SUCCESS: "COURSE_LOAD_SUCCESS",
  LOAD_FAIL: "COURSE_LOAD_FAIL",
};
const STUDENTS = {
  LOAD: "STUDENTS_LOAD",
  LOAD_SUCCESS: "STUDENTS_LOAD_SUCCESS",
  LOAD_FAIL: "STUDENTS_LOAD_FAIL",
};
const EXAMS = {
  LOAD: "EXAMS_LOAD",
  LOAD_SUCCESS: "EXAMS_LOAD_SUCCESS",
  LOAD_FAIL: "EXAMS_LOAD_FAIL",
};
const EMPLOYEES = {
  LOAD: "EMPLOYEES_LOAD",
  LOAD_SUCCESS: "EMPLOYEES_LOAD_SUCCESS",
  LOAD_FAIL: "EMPLOYEES_LOAD_FAIL",
};
const SERVICE = {
  LOAD: "SERVICE_LOAD",
  LOAD_SUCCESS: "SERVICE_LOAD_SUCCESS",
  LOAD_FAIL: "SERVICE_LOAD_FAIL",
};
const VENDORS = {
  LOAD: "VENDORS_LOAD",
  LOAD_SUCCESS: "VENDORS_LOAD_SUCCESS",
  LOAD_FAIL: "VENDORS_LOAD_FAIL",
};
const USERS = {
  LOAD: "USERS_LOAD",
  LOAD_SUCCESS: "USERS_LOAD_SUCCESS",
  LOAD_FAIL: "USERS_LOAD_FAIL",
};
const NOTIFICATION = {
  LOAD: "NOTIFICATION_LOAD",
  LOAD_SUCCESS: "NOTIFICATION_LOAD_SUCCESS",
  LOAD_FAIL: "NOTIFICATION_LOAD_FAIL",
};
const VENDORLOGIN = {
  LOAD: "VENDORLOGIN_LOAD",
  LOAD_SUCCESS: "VENDORLOGIN_LOAD_SUCCESS",
  LOAD_FAIL: "VENDORLOGIN_LOAD_FAIL",
};
const ORDERS = {
  LOAD: "ORDERS",
  LOAD_SUCCESS: "ORDERS_SUCCESS",
  LOAD_FAIL: "ORDERS_FAIL",
};

export {
  LOGIN,
  STUDENTS,
  EXAMS,
  EMPLOYEES,
  COURSE,
  USERS,
  VENDORLOGIN,
  SERVICE,
  VENDORS,
  NOTIFICATION,
  ORDERS,
};
